[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
    bblanchon/ArduinoJson@^7.0.0

build_flags =
    -DARDUINOJSON_ENABLE_PROGMEM=1
    -DARDUINOJSON_ENABLE_ARDUINO_STRING=0
    -DARDUINOJSON_ENABLE_ARDUINO_STREAM=0
    -DARDUINOJSON_ENABLE_NAN=0
    -DARDUINOJSON_ENABLE_INFINITY=0
    -Os  ; Optimize for size
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
